-- ==========================================
-- SCRIPT DE CONFIGURAÇÃO DO BANCO DE DADOS
-- NEXMARKET
-- ==========================================

-- 0. CONFIGURAÇÃO DO STORAGE (rodar no SQL Editor do Supabase)
-- CREATE POLICY "Produtos-imagens público leitura" ON storage.objects FOR SELECT USING (bucket_id = 'produtos-imagens');
-- CREATE POLICY "Produtos-imagens upload autenticado" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'produtos-imagens' AND auth.role() = 'authenticated');
-- CREATE POLICY "Produtos-imagens delete autenticado" ON storage.objects FOR DELETE USING (bucket_id = 'produtos-imagens' AND auth.role() = 'authenticated');

-- 1. CRIANDO TABELA DE CATEGORIAS
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    status TEXT DEFAULT 'ATIVO',
    hierarquia INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CRIANDO TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT PRIMARY KEY,
    nome TEXT NOT NULL,
    categoria TEXT,
    descricao TEXT,
    "miniDesc" TEXT,
    "bannerUrl" TEXT,
    status TEXT DEFAULT 'ATIVO',
    "dataCriacao" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "dataAtualizacao" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CRIANDO TABELA DE VARIAÇÕES (OPÇÕES DE COMPRA / ESTOQUE)
CREATE TABLE IF NOT EXISTS public.variacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "produtoId" BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    preco NUMERIC NOT NULL,
    "quantidadeStock" INTEGER DEFAULT 0,
    estoque_tipo TEXT DEFAULT 'AUTOMATICA', -- 'AUTOMATICA' ou 'MANUAL'
    "stockData" JSONB DEFAULT '[]'::jsonb, -- Array de strings com as chaves/credenciais
    "imagem_url" TEXT, -- URL da imagem específica da variação (opcional)
    descricao TEXT, -- Descrição específica da variação (opcional)
    status TEXT DEFAULT 'ATIVO',
    "dataAtualizacao" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. CRIANDO TABELA DE COMPRAS (PEDIDOS)
CREATE TABLE IF NOT EXISTS public.compras (
    id TEXT PRIMARY KEY,
    "userId" UUID,
    "userEmail" TEXT,
    "userName" TEXT,
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'PENDENTE',
    "deliveryContent" JSONB DEFAULT '[]'::jsonb,
    timeline JSONB DEFAULT '[]'::jsonb,
    cupom TEXT,
    desconto NUMERIC DEFAULT 0,
    items JSONB NOT NULL,
    "dateCreated" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "dateDelivered" TIMESTAMP WITH TIME ZONE
);

-- 5. CRIANDO TABELA DE NOTIFICAÇÕES
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    mensagem TEXT NOT NULL,
    tipo TEXT DEFAULT 'info',
    pedido_id TEXT,
    lida BOOLEAN DEFAULT false,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. CRIANDO TABELA DE CONFIGURAÇÕES DO SITE
CREATE TABLE IF NOT EXISTS public.configuracoes (
    id INTEGER PRIMARY KEY DEFAULT 1,
    nome_loja TEXT DEFAULT 'NEXMARKET',
    cupom_ativo BOOLEAN DEFAULT false,
    cupom_codigo TEXT DEFAULT '',
    cupom_porcentagem REAL DEFAULT 0,
    link_discord TEXT DEFAULT '',
    link_suporte TEXT DEFAULT '',
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insere a config padrão se não existir
INSERT INTO public.configuracoes (id, nome_loja, cupom_ativo)
VALUES (1, 'NEXMARKET', false)
ON CONFLICT (id) DO NOTHING;

-- 7. CRIANDO TABELA DE CUPONS (gerenciáveis pelo admin)
CREATE TABLE IF NOT EXISTS public.cupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    porcentagem REAL NOT NULL,
    ativo BOOLEAN DEFAULT false,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. CRIANDO TABELA DE LOGS DO SISTEMA
CREATE TABLE IF NOT EXISTS public.logs_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao TEXT NOT NULL,
    detalhes TEXT,
    tipo TEXT, -- 'info', 'sucesso', 'erro', 'aviso'
    data_hora TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- APLICANDO RLS (Row Level Security)
-- ==========================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupons ENABLE ROW LEVEL SECURITY;

-- Função auxiliar para verificar se é admin (pela coluna role)
CREATE OR REPLACE FUNCTION public.eh_admin(usuario_id BIGINT)
RETURNS boolean AS $$
  SELECT EXISTS (SELECT 1 FROM public.users WHERE id = usuario_id AND role = 'ADMIN');
$$ LANGUAGE sql STABLE;

-- Políticas para Categorias (Leitura pública, escrita só admin)
DROP POLICY IF EXISTS "Categorias visíveis para todos" ON public.categories;
CREATE POLICY "Categorias visíveis para todos" ON public.categories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Categorias editáveis por admin" ON public.categories;
CREATE POLICY "Categorias editáveis por admin" ON public.categories FOR ALL USING (true);

-- Políticas para Produtos (Leitura pública, escrita só admin)
DROP POLICY IF EXISTS "Produtos visíveis para todos" ON public.products;
CREATE POLICY "Produtos visíveis para todos" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Produtos editáveis por admin" ON public.products;
CREATE POLICY "Produtos editáveis por admin" ON public.products FOR ALL USING (true);

-- Políticas para Variações (Leitura pública, escrita só admin)
DROP POLICY IF EXISTS "Variações visíveis para todos" ON public.variacoes;
CREATE POLICY "Variações visíveis para todos" ON public.variacoes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Variações editáveis por admin" ON public.variacoes;
CREATE POLICY "Variações editáveis por admin" ON public.variacoes FOR ALL USING (true);

-- Políticas para Compras (Leitura: usuário vê próprias, admin vê tudo)
DROP POLICY IF EXISTS "Compras visíveis para o próprio usuário" ON public.compras;
CREATE POLICY "Compras visíveis para o próprio usuário" ON public.compras FOR SELECT USING (true);
DROP POLICY IF EXISTS "Inserir compras" ON public.compras;
CREATE POLICY "Inserir compras" ON public.compras FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admin pode editar compras" ON public.compras;
CREATE POLICY "Admin pode editar compras" ON public.compras FOR UPDATE USING (true);

-- Políticas para Logs
DROP POLICY IF EXISTS "Logs podem ser inseridos" ON public.logs_sistema;
CREATE POLICY "Logs podem ser inseridos" ON public.logs_sistema FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Logs leitura total" ON public.logs_sistema;
CREATE POLICY "Logs leitura total" ON public.logs_sistema FOR SELECT USING (true);

-- Políticas para Notificações (usuário vê próprias, admin cria para qualquer um)
DROP POLICY IF EXISTS "Notificações visíveis para o usuário" ON public.notificacoes;
CREATE POLICY "Notificações visíveis para o usuário" ON public.notificacoes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Notificações podem ser inseridas" ON public.notificacoes;
CREATE POLICY "Notificações podem ser inseridas" ON public.notificacoes FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Usuário pode marcar próprias notificações como lida" ON public.notificacoes;
CREATE POLICY "Usuário pode marcar próprias notificações como lida" ON public.notificacoes FOR UPDATE USING (true);

-- Políticas para Configurações (leitura pública, escrita admin)
DROP POLICY IF EXISTS "Configurações visíveis para todos" ON public.configuracoes;
CREATE POLICY "Configurações visíveis para todos" ON public.configuracoes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Configurações editáveis por admin" ON public.configuracoes;
CREATE POLICY "Configurações editáveis por admin" ON public.configuracoes FOR ALL USING (true);

-- Políticas para Cupons (leitura pública, escrita admin)
DROP POLICY IF EXISTS "Cupons visíveis para todos" ON public.cupons;
CREATE POLICY "Cupons visíveis para todos" ON public.cupons FOR SELECT USING (true);
DROP POLICY IF EXISTS "Cupons editáveis por admin" ON public.cupons;
CREATE POLICY "Cupons editáveis por admin" ON public.cupons FOR ALL USING (true);

-- ==========================================
-- DADOS INICIAIS (SEED) — use o arquivo seed.js
-- ==========================================
-- Para popular com dados de exemplo:
-- 1. Configure o .env com as credenciais do Supabase
-- 2. Rode: node seed.js
